// import React from 'react';
import './App.css';
import {Slider} from './components/Slider';

// import {PolygonjsScene} from './components/PolygonjsScene';
// import {loadSceneAsync_scene_01} from './polygonjs/scenes/scene_01/autogenerated/loadSceneAsync';
// import {PolySceneWithNodeMap_scene_01} from './polygonjs/scenes/scene_01/autogenerated/PolySceneWithNodeMap';
// function onSceneReady(scene: PolySceneWithNodeMap_scene_01) {
// 	console.log('onSceneReady', scene, scene.node('/geo1'));
// }

function App() {
	return (
		<div className="App">
			{/* <PolygonjsScene
				key="scene_01"
				sceneName="scene_01"
				loadFunction={loadSceneAsync_scene_01}
				onSceneReady={onSceneReady}
			/> */}
			<Slider></Slider>
		</div>
	);
}

export default App;
